steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/app:latest', 
      '-f', 'app/Dockerfile', 
      '.'
    ]
images:
  - 'gcr.io/$PROJECT_ID/app:latest'
