services:
  pipeline_scrape:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-key.json
    volumes:
      - ./gcs-key.json:/app/gcs-key.json:ro
    command: scripts.scrape

  pipeline_dummy:
    build:
      context: ./pipeline
      dockerfile: Dockerfile
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/gcs-key.json
    volumes:
      - ./gcs-key.json:/app/gcs-key.json:ro
    command: scripts.dummy