output_files:
  raw:
    events: "data/raw/ufc_events.json"
    results: "data/raw/ufc_results.json"
    fighters: "data/raw/ufc_fighters.json"
    rounds: "data/raw/ufc_rounds.json"
  clean:
    events: "data/clean/ufc_events_clean.parquet"
    results: "data/clean/ufc_results_clean.parquet"
    fighters: "data/clean/ufc_fighters_clean.parquet"
    rounds: "data/clean/ufc_rounds_clean.parquet"
  transformed:
    results: "data/transformed/ufc_results_transformed.parquet"
    fights: "data/transformed/ufc_fights_transformed.parquet"
  event_urls:
    all: "http://ufcstats.com/statistics/events/completed?page=all"
    one: "http://ufcstats.com/statistics/events/completed?page=1"